#!/bin/bash

# Bersihkan terminal
clear

cat > /etc/pam.d/common-password<<-END
password	[success=1 default=ignore]	pam_unix.so obscure sha512
password	requisite			pam_deny.so
password	required			pam_permit.so
END

# izin eksekusi
chmod +x /etc/pam.d/common-password